apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8demourl-fe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8demourl
  template:
    metadata:
      labels:
        app: k8demourl
    spec:
      containers:
      - name: k8demourl
        image: kingmant/url_shortener
        ports:
        - containerPort: 3000
