apiVersion: apps/v1   # First part, what kind of project you want to make - create this whole template by just typing "d" once you have the K8 plugin installed
kind: Deployment

metadata:             # 
  name: ecommerce-fe-app

spec:                 # Creates the project object for K8
  selector:
    matchLabels:
      app: ecommerce-fe
  template:
    metadata:
      labels:
        app: ecommerce-fe
    spec:
      containers: 
      - name: ecommerce-frontend
        image: djtoler/dp9backend
        ports: 
        - containerPort: 3000
